dbt_training_nov2025:
  outputs:
    DEV:
      account: ZRRCXMK-ZQ02055
      database: DEV
      password: "Bajrangbali@025"
      role: TRANSFORM
      schema: BRONZE_AIRBNB
      threads: 4
      type: snowflake
      user: Vikki26
      warehouse: COMPUTE_WH
    UAT:
      account: ZRRCXMK-ZQ02055
      database: UAT
      password: "Bajrangbali@025"
      role: TRANSFORM
      schema: BRONZE_AIRBNB
      threads: 4
      type: snowflake
      user: Vikki26
      warehouse: COMPUTE_WH
    PROD:
      account: ZRRCXMK-ZQ02055
      database: PROD
      password: "Bajrangbali@025"
      role: TRANSFORM
      schema: BRONZE_AIRBNB
      threads: 4
      type: snowflake
      user: Vikki26
      warehouse: COMPUTE_WH
    
  target: "{{env_var('DBT_TARGET')}}"
